CREATE TABLE tema (
    idNumero NUMBER(3) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20),
    descripcion VARCHAR2(40)
);

CREATE TABLE categoria (
    idNumero NUMBER(3) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20),
    nivel INTEGER
);

CREATE TABLE editorial (
    idNumero NUMBER(3) PRIMARY KEY,
    nombre VARCHAR2(20)
);

CREATE TABLE literatura (
    idNumero NUMBER(3) PRIMARY KEY,
    nombre VARCHAR2(20),
    descripcion VARCHAR2(40)
);

CREATE TABLE libro (
    idNumero NUMBER(5) PRIMARY KEY,
    isbn VARCHAR2(13) UNIQUE,
    titulo VARCHAR2(30) NOT NULL,
    edicion INTEGER,
    fechaPublicacion DATE,
    categoria NUMBER(3) REFERENCES categoria(idNumero),
    editorial NUMBER(3) REFERENCES editorial(idNumero),
    literatura NUMBER(3) REFERENCES literatura(idNumero)
);

CREATE TABLE libroTema (
    codTema NUMBER(3) REFERENCES tema(idNumero),
    codLibro NUMBER(5) REFERENCES libro(idNumero),
    PRIMARY KEY (codTema, codLibro)
);

CREATE TABLE autor (
    idNumero NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE libroAutor (
    idAutor NUMBER(5) REFERENCES autor(idNumero),
    codLibro NUMBER(5) REFERENCES libro(idNumero),
    PRIMARY KEY (idAutor, codLibro)
);

CREATE TABLE usuario (
    idNumero NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(30),
    contrasena VARCHAR2(20),
    telefono NUMBER(10),
    email VARCHAR2(30),
    tipoUsuario VARCHAR2(10) CHECK (tipoUsuario IN ('Admin', 'Normal')),
    puntuacionDonacion INTEGER DEFAULT 0, -- Podría usarse para un resumen o métrica
    cantIntercambios INTEGER DEFAULT 0,
    cantDonaciones INTEGER DEFAULT 0
);

CREATE TABLE intercambio (
    idNumero NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipoIntercambio VARCHAR2(15) CHECK (tipoIntercambio IN ('Permanente', 'Temporal', 'Donación')),
    estado VARCHAR2(15) CHECK (estado IN ('En espera', 'Aceptado', 'Rechazado')),
    usuario NUMBER(5) REFERENCES usuario(idNumero), -- Usuario que inicia el intercambio/donación
    fecha DATE DEFAULT SYSDATE,
    fechaIni DATE DEFAULT NULL,
    fechaFin DATE DEFAULT NULL,
    cantDonada INTEGER DEFAULT NULL,
    puntuacionDonacion INTEGER DEFAULT NULL -- Podría usarse para registrar la "calidad" total de la donación
);

CREATE TABLE ejemplar (
    idEjemplar NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idLibro NUMBER(5) REFERENCES libro(idNumero),
    tipo VARCHAR2(10) CHECK (tipo IN ('fisico', 'digital')) NOT NULL,
    estadoFisico VARCHAR2(20) CHECK (estadoFisico IN ('Excelente', 'Bueno', 'Regular', 'Malo')),
    puntuacion INTEGER CHECK (puntuacion BETWEEN 0 AND 10), -- Podría representar una puntuación de calidad
    imagen BLOB,
    usuario NUMBER(5) REFERENCES usuario(idNumero), -- Usuario que tiene el ejemplar actualmente
    intercambio NUMBER(5) REFERENCES intercambio(idNumero),
    fechaAdquisicion DATE DEFAULT SYSDATE,
    aceptadoBiblioteca CHAR(1) CHECK (aceptadoBiblioteca IN ('S', 'N')),
    estadoBiblioteca VARCHAR2(20) CHECK (
        estadoBiblioteca IN ('Disponible', 'Prestado', 'Intercambiado')
    ),
    propietarioOriginal NUMBER(5) REFERENCES usuario(idNumero) -- Dueño original del ejemplar
);

CREATE TABLE libroLeido (
    idUsuario NUMBER(5) REFERENCES usuario(idNumero), -- Referencia al dueño de la biblioteca
    idLibro NUMBER(5) REFERENCES libro(idNumero),
    fechaLectura DATE DEFAULT SYSDATE,
    PRIMARY KEY (idUsuario, idLibro)
);

CREATE TABLE detalleIntercambio (
    idDetalle NUMBER(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idIntercambio NUMBER(5) REFERENCES intercambio(idNumero),
    idEjemplarOfrecido NUMBER(6) REFERENCES ejemplar(idEjemplar),
    idEjemplarRecibido NUMBER(6) REFERENCES ejemplar(idEjemplar),
    tipoRol VARCHAR2(10) CHECK (tipoRol IN ('Ofrece', 'Recibe')), -- Para distinguir qué ejemplar se ofrece y cuál se recibe
    cantidadOfrecida INTEGER DEFAULT 1, -- Para el caso de múltiples libros de baja categoría
    CONSTRAINT unicos_ejemplares_intercambio UNIQUE (idIntercambio, idEjemplarOfrecido, idEjemplarRecibido, tipoRol)
);

CREATE TABLE donacionEjemplar (
    idDonacion NUMBER(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario NUMBER(5) REFERENCES usuario(idNumero),
    idEjemplar NUMBER(6) REFERENCES ejemplar(idEjemplar),
    fechaDonacion DATE DEFAULT SYSDATE
);

CREATE TABLE recompensaDonacion (
    idRecompensa NUMBER(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario NUMBER(5) REFERENCES usuario(idNumero),
    idEjemplar NUMBER(6) REFERENCES ejemplar(idEjemplar),
    fechaRecompensa DATE DEFAULT SYSDATE
);