CREATE TABLE tema(
    idNumero NUMBER(3) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20),
    descripcion VARCHAR2(40)
);

CREATE TABLE categoria(
    idNumero NUMBER(3) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20),
    nivel INTEGER
);

CREATE TABLE editorial(
    idNumero NUMBER(3) PRIMARY KEY,
    nombre VARCHAR2(20)
);

CREATE TABLE literatura(
    idNumero NUMBER(3) PRIMARY KEY,
    nombre VARCHAR2(20),
    descripcion VARCHAR2(40)
);

CREATE TABLE libro(
    idNumero NUMBER(5) PRIMARY KEY,
    estado VARCHAR2(50),
    titulo VARCHAR2(30) NOT NULL,
    tipo VARCHAR2(10) CHECK (tipo IN ('fisico', 'virtual')),
    edicion INTEGER,
    fechaPublicacion DATE,
    tipoAgregado VARCHAR2(15) CHECK (tipoAgregado IN ('Pertenencia', 'Donación', 'Intercambio')),
    nivelAfinidad INTEGER,
    categoria NUMBER(3) REFERENCES categoria(idNumero),
    editorial NUMBER(3) REFERENCES editorial(idNumero),
    literatura NUMBER(3) REFERENCES literatura(idNumero)
);

CREATE TABLE libroTema(
    codTema NUMBER(3) REFERENCES tema(idNumero),
    codLibro NUMBER(5) REFERENCES libro(idNumero),
    PRIMARY KEY (codTema, codLibro)
);

CREATE TABLE autor(
    idNumero NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE libroAutor(
    idAutor NUMBER(5) REFERENCES autor(idNumero),
    codLibro NUMBER(5) REFERENCES libro(idNumero),
    PRIMARY KEY (idAutor, codLibro)
);

CREATE TABLE usuario(
    idNumero NUMBER(5) PRIMARY KEY,
    nombre VARCHAR2(30),
    contrasena VARCHAR2(20),
    telefono NUMBER(10),
    email VARCHAR2(30),
    tipoUsuario VARCHAR2(10) CHECK (tipoUsuario IN ('Admin', 'Normal')),
    puntuacionDonacion INTEGER DEFAULT 0,
    cantIntercambios INTEGER DEFAULT 0,
    cantDonaciones INTEGER DEFAULT 0
);

CREATE TABLE intercambio(
    idNumero NUMBER(3) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR2(15) CHECK (estado IN ('En espera', 'Aceptado', 'Rechazado')),
    usuario NUMBER(5) REFERENCES usuario(idNumero),
    fecha DATE,
    fechaIni DATE DEFAULT NULL,
    fechaFin DATE DEFAULT NULL,
    cantDonada INTEGER DEFAULT NULL,
    puntuacionDonacion INTEGER DEFAULT NULL
);

CREATE TABLE ejemplar(
    idLibro NUMBER(5),
    puntuacion INTEGER,
    imagen BLOB,
    usuario NUMBER(5) REFERENCES usuario(idNumero),
    intercambio NUMBER(3) REFERENCES intercambio(idNumero),
    PRIMARY KEY (idLibro)
);